/*
 * Copyright (c) 2015. PathOS Variant Curation System. All rights reserved.
 *
 * Organisation: Peter MacCallum Cancer Centre
 * Author: doig ken
 */

package org.petermac.pathos.pipeline

/**
 * Created for PathOS.
 *
 * Description:
 *
 *
 *
 * User: doig ken
 * Date: 23/03/2015
 * Time: 7:55 AM
 */
class CanaryTest extends GroovyTestCase
{
    void testRegex()
    {
        def str = 'gataca'

        def m = ( str =~ /t(a)c/ )

        println m
        assert m.count
        println m[0]
        println m[0][1]
    }

    void testConstructor()
    {
        def can = new Canary()
    }


    void testRunCanary()
    {


        def can = new Canary()

        String resource = "Canary/Sub"
        String file = "CancerGNA10212011_170_190_Viewermanifest"
        String extension ="fasta"
        File ampfile = new File(CanaryTest.getClass().getResource( "/${resource}/${file}.${extension}" ).getPath())

        String amplist = "KIT24_28.chr4.55599320.55599348_tile_1, KDR1.chr4.55946114.55946257_tile_1, GNAQ_5.chr9.80409379.80409508_tile_1, PTEN13.chr10.89720716.89720852_tile_1, PTEN13.chr10.89720716.89720852_tile_1"

        file = "CancerGNA10212011_170_190_Viewermanifest"
        extension = "fasta.primers"
        File primfile = new File(CanaryTest.getClass().getResource( "/${resource}/${file}.${extension}" ).getPath())

        def vars = []

        String basepath = primfile.getParent()
        File ofile = new File("${basepath}/canary.out")

        file = "canary"
        extension = "vcf"
        File vcffile = new File(CanaryTest.getClass().getResource( "/${resource}/${file}.${extension}" ).getPath())

        file = "14M6168_AACCCCTC-TAGACCTA_L001_R1_001"
        extension = "fastq.gz"
        File r1 = new File(CanaryTest.getClass().getResource( "/${resource}/${file}.${extension}" ).getPath())


        file = "14M6168_AACCCCTC-TAGACCTA_L001_R2_001"
        extension = "fastq.gz"
        File r2 = new File(CanaryTest.getClass().getResource( "/${resource}/${file}.${extension}" ).getPath())

        Double pct = 0.0

       assert can.runCanary(  ampfile,  amplist,  primfile, vars,  ofile,  vcffile,  r1,  r2,  pct ) == 2000
    }

    //Todo: load variants is not used anymore
//    void testLoadVariants()
//    {
//
//        def can = new Canary()
//
//            List<List> vars = [ ["4", "55599436", "T", "C","13/13", "chr4:g.55599436T>C"],
//                                ["4", "55946081", "A", "G", "12/12", "chr4:g.55946081A>G"]
//                              ]
//
//
//            List<Map> amplicons = [ ["name":"KIT24_28", "pos":"55599436", "fwdlen":55599290, "revlen":55599472],
//                                    ["name":"KDR1", "pos":"55946081", "fwdlen":55946114, "revlen":55946257]
//                                  ]
//
//        int readlen = 10
//
//        println "TESTING with: ${amplicons} AND ${vars} "
//        println can.loadVariants( amplicons,  vars, readlen )
//        println "DONE"
//        assert true
//    }

    void testRegExp()
    {

        String bases = "gataca"
        boolean dir = false
        int offset = 0

        Map var = ["chr":"4","pos": "55599436","ref": "T","alt": "C", "chr_pos_ref/alt":"13/13", "hgvsg":"chr4:g.55599436T>C"]


        def can = new Canary()

       assert  can.regex(  bases,  offset,  dir,  var ).toString() == "ataca(A|G)ataca"
    }

    void testSAMFileWriter()
    {
        def can = new Canary()

        String bamFile =  "BamOut.bam"
        String sample = "14M5511"
        String readGroup = "ID"

        //
        // This returns a string with the initial pattern as  htsjdk.samtools.BAMFileWriter@...
        assert can.openBam(  bamFile,  sample,  readGroup ).toString().split("@")[0] == "htsjdk.samtools.BAMFileWriter"

    }

//    // Todo: NOTE wht readX.bases from 0 .. 250
//    void testIgvhStats()
//    {
//        def read1 = ["bases":"ATTTTATTTTAAACAAAATAAGAACTCAAGGAATAAGAGGGTTCTTCCAATAGGTTAGAGTGATCCTGTCAAACATATATGCTTCTAGATTTTTTTAAAGACTGTTTCTACTAAGAAAGCATAGACCGCTATTGAGAAAGATCATTAAACTGGAATTTAGGAGGTCTGCCTTCTGATTCTGACTTCTTGAATGTATTGTTAGCCATTTAACCACACTGTGTTGTTTCTCATTCTACCTGTAGAATCTCAAAGTTCTTTCCCACTTCTATACAAAACTATAATTCTGAACATCCTTTTTGTTTAATATAAGTCTGCATTTCCTGTTTGAAGATATGTGTCCCAGACCCTAAATGACTGACAAATTTTAAATCTCCAATAGGAAAGATGACAAACTCTATGGAAACTTGGCTTCTGAAGAACTCCTAGAAGCTTTCCAAAGTCATCAGTGTTTCCTAAGAAGGCAGAGAAATCAAACACATGGTCTTTTCCTCCAGACAAGCTCCTTTGGGTCATCAGGATTTCTTCAACAATAAAATGTAATAATTCCAAATGTTTGTAACAGAATGGGTAGGACTTTCTTCACTTATTTAAATACTCCCTTTTTTATGCAACTGAGTTTTCATCAACAAGTACAAGCTTGTGAAGGAGTACTTTAAAATGCAATTTCTCTCTATTTTTGTGGGGGCTAATATTTTATTTCTCATATTGACAATTTATTATGCTGTTTTTAAAAAGTTCATTCATCAAGTATTTCTTGAGCTTTTTCTATGAGACAGGCACTGTTTTAGGCAAGTAATTATGCACTGAACAATGCAAAAAGTTTCCCTGCACTCATGGACTTTAATTTTACATTTATGAAAAGCTACAAATATTAGAATAAGTAAAATACTGCCTGGAGGCTAAAGCATATTTTGATCACTTATTCCCTAATTCTTTTAGAAGAGAACTCACCTGTCGGTTAGCTGAACCACTGCCAGTGATATCCAACTATACATTCAATCCCACCATACCTCATTATCACACCTATTCACTCACAAGCTTAAACTCTTAACTTTTCTCCACATATCAGTGACTATTTCCTACAGCTTTTCTTTTACTTTCCATGTTTGCAGTGACAATATACATAAACAGTGTATGAAAACTCAAGTAAAATCTACTCTCTCAGGTGTTCATAATGTATCAATGTATATTGCTTTAAGCCTGAAGGTAACCTAAGTAAAGATGTACCATGTTCCACCAATGCTTCTTTTGATCATCATTTTATCCTGTTTTTTCTTTAGGATTCTTTCTTATTCCTTCCCCTGACCCTTCTTTTATTCTCCAAATTTCTTTCCAATTCATCTTTGTTCTTCCCTTTCCTTTTTACTCTCTTTAAACATTCTATGGACTCTGCCTCCTTCACACTGATATTGAACGCCCATAGTTTCATATTTTGGATTGCGATTGTTTTATTTTAAAATGGCAAATGTTCATGTTATAAAGAGAATTTTTCAGTCTTTAGACTAATAGGTTCATGTAGTTTGGGATTTTCCTCTTTAAGAAAATTAATTATCACTCACACTCCAAGACAAACACCATTTCAGTAGCAATATGAATTTCAGTAGTAATAGGAATCTCCAAATATGACAAAGTAATTCAGACATTAATTGCTTTTGTTTTGGAATTGCTCTTATAAGATGAAATATCACTTTCATGATGAGAGTCCTAGAGTGCTTGGTTTATATATTGTATCTTAGTTTTAACAGGATAAAACACTTGATCCTAAGCAGTAAACATGATTCTTCAGCTTCAACTTCATTTCTTTATAAATAACTATTTATGAATTGGTGTTGAGCTTAGTAAGTCACCAAACACCTTCTGCTCAGCAGCATAAAGGACATTTCCATGAAACCTCCCAGGGATAATCTTATTTACTCTATAATGTTTCCCGGGTTCAATTCCTCTCCCAAAATTCTTTGTTCTTAAGCCCCTATGATCTGGGTGATCTAAATATGGGTAAGAAGTCCAGGGATAGCACTATGAATGAAGTGAAAATAGTAAAACATAGTTAAAAATGTACAGATGCTCTCTGACTTATAATAGGGTTACGTCCTGATAAATCCATCATAAGTCAAAAATGCATTTAATATTCCTAATGTACCTCACATCATAGTTTGGCCTAGCCTACCTTAAATGTGCTCAGAACACTTTCATTAGCTTATATAAGATCACCTAATACAAAGCCTATTTTATAATAAAATATTGAATAGCTCACGTAATATACTGACTACTATACTCAAGTACAGTTTCTTCTGAATGCATGTCACTTTCTCACCATTGTAAAGTCAAACAATTATAAGTCAAACTATCACAAGCCAGGGACCATCCATATGTATTTCATTCAGAAAATGCTGGAAAGAGCATTTCGGAGAATATCTAGATGAGAGAAGGTAGAAAGCCATGCACAAATTCACTGAGAGTTTAAAAAAATACATGCATATTGTGGAGATAGAAATCAAATCTATTTGTCTCCATCTGCTGTATTCTTCCCAAAATATTATCTCTTCTTATCCCATTGTACTATATTGCATTTCTTTGACCATTTATTGTGTATCTCTTAATATTTCCCACTTCATCATTACTAACCTCACTCACTCTGAACTTGATGAGAGCACCTGAGCATTAATTTTTCTTATAATTATTTAATGATTACCAGAATTCGTTCAGTATGGCCAGCTCTGGTCAAAGTGAGGCAGGCAAGATGCTTTGTCAACTGCCTGGATGGAATGTCTCAAAAGGTTTCCATTTCATGGTAGCATTATGCAAAGTTCAAGACGTTTAATCAAGACCCTTCACTTACTTAACTATACCTCCTTGAGAATCCCATCTATGAAAAAATTCTAGTCATTATAAAAATGATTGATTAAATGAGGGAAGTAGTAGAGTTCTTCATTTCTTTAGTTGGTTTAGTCTCCTATGAGTCAATCCTATTTTCAAAATTCTTAATAAACCATTTATTCCTTCAACTTTCTATGCCATTTGATGTTTTGTAAAAAAAAAAATATAATATGTATACAAAAAGATATTTCAAAATCTAGAAAGAGAGCTTTAGAGCTTTGTAAAGCTCTTTTAAAAATCAAAAACAACTACTGTTAATTAACATGTTGTACTATGCAATTTGTTTACCATTATTACTCTTGGTATTTTTAAGAAAAGTCTTTCCATTGTTATTATAAATGCTTCTATTGATATTTATTTTAATAACTGTTATTACAGTCCGTCATGTACATACACTATACTTAAACCTAATGTTTGGTATTTAAATCGTTTCAAGATTTTATCACTGTCAACAAAGTATGATGAATATTTTTATGCTGAAAACTTCTGTAAAAATAGAATTCCAAGAGTATTATTGCACCAAAAGGCATGGACTTAAAATTCTTGATACATGATTTCAAAATATTTTCTTTAAGGTTTGAATCAGTCTATATTCCCTCCAGCAGCGTATAAAAGTGCCAATTTCTCTGATCCTTAGCCAGTTTGGGTAATAATAATTGTAAAACTTTTTTTTCTTTTTTTTTGAGACAGAGTCTCCCTCTGTCGCCAGGCTGAAGTGCAGTGGCGCAATCTCGGCTCACTGCAACCTCCGCCTCCCGGGGTCAAGCTATTCTCCTGCCTCAGCCTCCCAAGTAGCTGGGACTACAGGCATGCACCACCATGCCCAGCTAATTTTTGTTATTTTTAGTAGAGATGGAGTTTCCCCATGTTGGACAGGATGGTCTCGATCTCTTGACCTCGTGATCCACCCTCCTCGGCCTCCCAAAGTGCTGGGATAACAGGCGTGAACAACCATGCCCGGCCTGTAAAACTTTTTCCTAATTTAACAGAAAAATAATAGTATTATATTTTATCATATTTCTTTGATTTCTAAGACACACATACACACACACACACACATATCTGTATATACAAATACACGTATAGCTTACATTTTAATTCTTCATTTCATTTGTTCATTTATTAGGTCTTGGAGATTTTGTGAAACTGTTTAAATTCTTTTTTATACTATGAAGATATCAACCTTTTGTCTCTACAGCATTTCAAATTCAAGTATGATTCACGTGTTGGTTTGGGGTAGATCATTATAGGCACATGTAGGAAACAGCTTTCAGAGATGCCTTAACCGTAATTATGCATTTGTATTCTAATTTTTATTTAATGTTATTATTGATTGCATTTTTAAAGATTCTGTATTTTTTAAACCATTTATTTGTATATGTTGGTATACAATCTTGCCATTTTCTGGGATTTCATATTTCCTTATTTTTGTTTTTTACCTTTTTTGGCTTGAATTTTTTGAGTTTTTATGCATTCTTTTCCAGTTTCTTAAGATGCTAATAAGTTCATGTATTTGAGCAATTGAGAACATTTAAAGCAATAGACTGCCTCTGAGCACAGCTTTGTCCATATTACATTAACCTTTTATACCCTGGGTTCCCACTAGTTTTTAAATAATCTACTATCAAATAAAAGATTTGTTAATAATAAATTTTAAATCATTAACACTTAACGCATTATTTTCAGTCACACTAAGTTGATTCCTTCGTTTCTTTCAGGTTGCTTCAGAGTCTTCCCTTCTATCTGATTCAGTGGACCAAGTAAATGACTCTCTGGTAACAGAATTTGTATTACTTGGACTTGCACAATCCTTGGAAATGCAGTTTTTCCTTTTTCTCTTCTTCTCTTTATTCTATGTGGGAATTATCCTGGGAAAACTCTTCATTGTGTTCACAGTGATCTTTGATCCTCACTTACACTCCC"]
//        def read2 = ["bases":"GGGGTTTTGCCATGATGGCCAGGCTGGTCTCGAACTCCTGACCTCAGGTGATCCTCCCGCTTTGGCCTCCCAAAGACTTTTTTTTTTTTTTTAATATAGAGACAAGTTCTCAGTACGTTGCCCAGGCTGGTCTCAAACTCCTGAGCTCAAGTGATCCTCCCACCTCAGCTTCCCAAAGTGCTGGGACTGACTGGATGCAGTGGCTCATGCTTGTAAACTCAGCACTTTGGGAGGCCAAGGTGGGAGGATCGCTTGAGCCCAGGAGTTCAAGACCAGACTGGGTGATATAACACAATAGTCAACTTCAACAGGAGAGAGAATCTGTAAACTTGAATATAGATCTTCCGAAATTATCCAGTCAGTGGACAGAGAAAAAAAGAATAAAAGAGAGAAAAGAAGGCTGGGTGTGGTGGCTCAAGCCTGTAATCCCAACACTTTGGGAGGCCGAGGCAGGCAGATTAAGAGGTCAGGAGTTCAAGACCAGCCTGTCCAACATGACAAAGCCCCATCTCTACTAAAAATACAAAAATTAGCCGGGTGTGGTGGCACACACCTGTAGTCCCAGCTACTTGGGAGGCTGAGGCAGGAGAATCGCTTGAACCCAGGAAGCGGAGGTTGGAGTGCAATGTGAGCCGAGACCACACATTACACTCCAGCCTGGGTGACAGAGCATGACTCTGTCTCAAAAAGAAAAAAAAAAGAGACAGAGAAAAGAAAGCCAACAAGACACCATTAAGCAAACCATTGTCAGGTTATGGGAGTTTGAGAAGGAAAGTAGAGAAAGGAGAATAAAGCTTATTTAAAGAATGGCTGACAACTGCCTAAATCATGGGAAAGATTTAGACATCTAAATCCATGAAGCTTAAAGATTCCTAAAGAGGTTCAAACCAAATAGATACTCACCAAGTCACAATATAATCAAATAGTCAAAAGTTAAAGAAACTTTGCAGGTCAGGACAGAATCGAATAATACATTCAAAGTGCTGAAAGAAAAAAACTGCCAGCAACTAATACTATGTCTGACAAAGCTGTCCTTCAGAAAGGAAAAAGAAATAATGTGTTTCCTCGACAAACAAAGCTGAGGGCATTCAGGACCACTAGGTCTACCTTAAAAAAATGCTTAACGGAGTTTTTCAAGTAAAAATGAATGAAGTTGGGAGCGGTGGCTCATGCCTGTAATCCCATTTTGGGAGGCTGAGGTGGGTGGATCACCTGAGGTCGGGAGGTCAAGACCAGCCTGGCCAACATGGCAAAACCCCACCTCCAGTAAAAATACAAAAAATTAGCCAGGTATGAAGGCCACTGAGATCGTGCCACTGCACTCCAGCCTGGGTGACAAGAGTCAAACTACATTTCAAAAACAAAAAACAAAACAAACAAAAAAAACAAAACTTGAGGCCTGGCCTTCTGCTCCTCTCCAACCTCCCCTTCTCTGGGCCCAAGCCACCTTGGCTGAGGAGGGGGCGAGGAGGTGTGAGCCCCTGCCAGGAACCCCCTGCCCGGACCAAGTGCTCGGCCCCCAGGCCTGCGTTCAGTGAGGCCTCCCGTGGCGTCAGCATGTTCGTGTGGAGGAATGTGGAAGGTCACTCTGCGGCCGTGTTCTCCTGGTACTCCATCCCCTTCCTGACCCCTCCCTGCAGCCACACGAGGCCCAGCAACCTGCCAGTCACTCAGTGGCCTCCAACCAGAGAAAACAACCTGCCAAGTTGGCAGCTGTTGCTCATGAGCGTCCACCAGGTGGGACAGGGAGTGTTGACCCTGGGCGGCCCCCTGGAGCCACCTGCCCTGAAAGCCCAGGGCCCGCAACCCCACACACTTTGGGGTTGGTGGAACCTGGTAAAAGCTCACCTCCCACCATGGAGGAGGAGCCCTGGGCCCCTCAGGGGAGTCCCTGCTGGACAGTGAGACAGAGAATGACCATGATGATGCTTTCCTCTCCATCATGTCTCCTGACACCCAGTTGCCTCTACCACTCAGATGATGTCAGGCCCAGTCCCTCAGTGCCCTGCGCAAGGAACAGGACTCATCTTCTGAGAAGGATGGACGCAGCCCCAACAAATCAGACAAGGACCACATCCGGTGGCCCATGAGTGGCGCTCATGATCTTCAGCAGGCGGCACCAGGCCCTGGCGGGGCGCACCAGGGTCACCCCAACCAGGATAACCGGACCGTCAGCCAGATGCTGAGCGAGCGGTGGTACACCCTGGGGCCCAATGAGATGCAGAAATACAACCTGGCCTTCCAGGTGAAGGTGGCCCACTTGCAACAAGGACCGAAAGAAGTCCAGCTCAGAGGCCAAGCCCACAAGCCAGGGGCTAGCAGGAGTGTAACAAGGGCTCGTGGGAGCGGAGCATATCAGAGACGGGCACTGCCACTGCCCCTGGGGTGTCCTCTGAACTCCTGTCAGTTGCAGCCCAAACACTCCAGAGCTCGGATACCAAGGAGCAGCTTCTGTGGGGCAGAACGGCTGCACACAGTCAGGGAACCTGGCTCAGCCTGGCCCAAGCCTTCTCCCACAGCGGGGTACACAGCCTGGACGGCAGGGAAATAGACCGTCAGGCACTACGGGAACTGACACAGGTGGTGTCTGGCACTGCATCATACTCTGGCCCAAAGCCTTCTACTCAGCATGGAGCTCCAGGCCACTTTGCAGCCCCTGGTGAGGGAGGTGACCCGTGGGCAGCCCTGCTGCCGCCCACGTGAGCTGCTCATTCCCAGCACATGGCCAGCGAGGTCATAGCGAGTGACGAAGAGCACACGGTCATCCATGAGGAGGAGGGGGTGATGATGTCATTGCTGATGATGGCTTTAGCACCACCGACACCGATCTCAAGTTCAAGGAGTGGGTGACCGACTGAGAGTGGGGACAACTCTGGGGAGGAGCCAGAGGGCAACAAGGGCTTTGGTGGGAAGGTATTTGCACCTGTCATTCCTTCCTCCTTTACTCCTGCCGCCCCTTGCTGGATCCTGAGCCCCCAGGGTCCCCCGATCCACCTGCAGCTTTTGGCAGTCTATGGTCACACCCTGTCCTCCTCCTACACATACTCGGATGCTTCCTCCTCAACCTTGGCACCCACCTCCTTCTTACTGGGCCCAGGAGCCTTCAAAGCCCAGGAGTCTGGTCAACGCAGCAGAGCGGGCCCCCTACGGCCCCAACCCCTGGGGATGGGGGCCCAGGGACGCCTTCCAAGGTGGCCTGTTTCCTCCCAATGGATCCTGCCACCTTCTGGTGCAAGAGACCTGAAAGTGTGGGCGACCTGGAGCTACCAGGCTCCTCAGTCATCAGGGTCCCTCCCAACACTAAGGCTTTCCTAGGCAGGAGCTGGGCTGAGCCACCCGGGGGGCAGAGCCTGAAGAGAAACTGACTGGGCTTTCGGGGTCGGGGCAGAGGGAACCCCACGGACATGGACCCCACACTGGAGGACCCCACCGCGCCCAAATGCAAGATGAGAAGATGCTCCAGCTGCAGTCCAAAGCCCAACACCCCCAAGTGTGCCATGTGTGATGGGGACAGCTTCCCCTTTGCCTGTACAGGTGGAGAAGCCGAGGACAGGCTCAGGGAACCGGAGACCAAGAAGGCGCTGTCCTCTTCACTGCATGTACCCTGGACCAGTGCCGGCCCTGATCATGCAGCTCTTCCAGGCCCACTGCTTCTTCCTGTCCACTAGGCCACAGCCGCCCTCCAGGCCCACTATGCACACATCTTCCCCTCCAAGGTTTGTTCTGCCCCTGCCCTGACTCCCAGCCCTGTGGGGGTCCTGACCGCACCTCACCTGGCTCAGACTCTTGACGCTGCCCTGGCTGCCCCACCAGTGCTTCTGCCCGAGAGTCACGTGAGGCTGAGAGTAGGGGCAGGGGCAGCAGTGGTGCCAGTTGGGGGGCGGTCCAGTGGGAGGAGCCTCAGCCTCGCAGGCTGCTCCGTGGGACTGATGACTGCATGATCTTCTGGGCACCTCACGGATCTTCAACTGCAGGTGAAACGGATGCTGGTGGTGGGTGCAGGGCCGCTGGGAGCTGCTGCATGGTTCCCAGAGGCTGGACTGAGGCAGGTGCCAACTGAAGCTGCTGGGGCAGCATGGGCAGGATGTTCTGCACACAAACCTTGGAGAAGAAGATGTGTGCATAGCAGGTCCACTGCTGCTGCCCCTGCCCTGACTCCCAGCCCTGCCTGACCCCACCTCAACCTGCTCAGGCTCTGGCACAACCCTGGCTGCCCTGCCACTGCCTCTGCCCCAGAGTTGGTGCCTTGACAGCCTGGTTGGAAGGGGACACCCCAGCCCTGCCTCAACACCTGGGGGTCTCCATAACTAGCACAGGCAGGTGGGCAACCCCAAAGATCCCAGGACTCACAGTACCCCCTGAGAACATGGACAGTATGTGGGGGTAGCAATGGAGGGCAGGATGGTTATCTTCTCCCAGGTGAAGCCATTTAATCCTTTCAGTTTGGGACGGAGTAAGGCCTTCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTGAGACCGAGTCTTGCTCTGTCGCCCAGGCTGGAGTGCAGTGGTGCGATCTTGGCTCACTGCAACCTCTTCCCGCTGGGTTCACGCCATTCTCCTGCCTCAGCCTTCCGGGTAGCTAGGATTACAGGTGGACGCTACCACGTCCGGCTAATTTTTGTATTTTTAGTACAGACGGGGCTTCATCATCTTGGCCAGGCTGATTTCGATCTCCTGACATCGTGATCTGCCTGCCTCCCCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACCACGCCTGGCCAAGGCCTGCTCCTCTTATCTATACCCCCTACCCCTGCAGCTGTGCCGGGGGAAAGCTGGGCAGTTTCCCTCCTCCGAGCCCCTGTACATACCATGAATTGTGGGACCTTCAGAGCTTTTCACTTTTCGGAAAATAGCTCCTGCTGGGGCTACAAGATGGAGTGTGAAGAGGGCCTTGGGCCACAGGGAGGCGCCTGTGGACTAGGGGGAGTTCATGCACCCCTTCTTTCCCCAGAGGGGCTGGACTCAGGTGAGTATGGGGGTGGGGGCTCCTGCACTTCGACACAGGCAGCAGGAGGGTTTTCTCCCCATTCCCTCTGCACTCCCAACTTGAGCTATACTTTTTAAGAAAGTGATTCACCCTGCCTTTGCCCCCTTCCCCAGAACAGAACACGTTGATCGTGGGCGATATTTTTCATTGTGCCAAAAAGTTGCCATGACCGTCATTAAACCTGTTTAACACCAAATAATAAGGAAAATAAAATAAAAAATTCGGGCTTGGCGCAGAAACTCACTCCAAATAAATTACCTACCAAAACATTTACATAATGGTGGAAATATTCCAAAATTCAATATTTTGGGATTTATACACAAAAGATAAACAAATTAGAGGCCAAGAGGCTGCCGGAAGGGAAAAACAGGGCCTGGAATGGCCGACGTGAGGAATGAGCTGGGCCTAAAGAGGCCACTGGCAGGCAGGAGCTGGACCTGCCGAAGTGGCCGAAAGGCAGGAGCTTTGGACTGGGGAGGCCGCAGTGAGGCGAGAGCTAGCTGGGCGTGGAGAGTCCGCTGTGAGGCCGAGGCCGAGGCTGGGCCCGTGCAGGCCTTCGAGACGCAGGAGGCCGGGCCTGCAAAGGCCGACTGGAGATCAAGTTCTGCGCCTGAAGAGGCTGCCAAAAGTCAAAAGCGGGGCCTGGGAAGGCCGCCGAGAGCCATGAGCTGGGCTGGGCCGAAAGAGGCCACTGGGAGGCAGGAGGAGCTGGGCCTGGAGAGGCTGACTCGAGGAAGTTTTGCACCTGGAGAGGCCGTCGAGAGGACGGAGCTGGGCCCAGGGAGGCCGACTTGCTGCTCTTCCAGGCCCACTTCCAGGCCGACTTGAGGACGACT"]
//        def stats = [:]
//
//        def can = new Canary()
//       println read1.bases[0..250]
//
//        //can.igvhStats( read1, read2, stats )
//    }

}
